cargo-features = ["default-run"]

[package]
name = "rine"
version = "0.1.0"
authors = ["Jeremy Soller <jeremy@system76.com>"]
edition = "2018"
default-run = "rine"

[dependencies]
env_logger = "0.6"
libc = "0.2"
log = "0.4"
redox_syscall = { path = "syscall" }
sc = "0.2"
