[package]
name = "rine"
version = "0.1.0"
authors = ["Jeremy Soller <jeremy@system76.com>"]
edition = "2018"

[dependencies]
env_logger = "0.6"
libc = "0.2"
log = "0.4"
redox_syscall = { path = "syscall" }

[target.'cfg(target_os = "linux")'.dependencies]
sc = "0.2"
